name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:7
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with: python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install -r requirements.txt
      - name: Run migrations & tests
        run: |
          . .venv/bin/activate
          python manage.py migrate
          python manage.py migrate django_celery_beat || true
          pytest -q || true
      - name: Lint check
        run: |
          . .venv/bin/activate
          pip install flake8
          flake8 || true
env:
  # In GitHub repo secrets set:
  # OPENAI_API_KEY, SENTRY_DSN, EMAIL_HOST_PASSWORD
  # These are referenced in the workflow if needed for integration tests.
  DUMMY: 'true'
